language: cpp
compiler: gcc

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
before_script:
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
script:
 - export CC=gcc-7
 - export CXX=g++-7
- cmake .
- cmake --build .
- cmake --build . --target package
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
  script:
  - curl -T  print-ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -EagleEyesRD:$BINTRAY_API_KEY "https://travis-ci.com/github/EagleEyesRD/otus-print-ip/$TRAVIS_BUILD_NUMBER/print-ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
